import { Code, NestedCode } from "./source-code.js";

export function formatData(content: unknown) {
  return JSON.stringify(content, undefined, 2);
}

export async function formatCode(nestedCode: NestedCode) {
  const banner = `
// @generated by
//
//   ██████╗ ██████╗ ███████╗███╗   ██╗ █████╗ ██████╗ ██╗██╗  ██╗██████╗ 
//  ██╔═══██╗██╔══██╗██╔════╝████╗  ██║██╔══██╗██╔══██╗██║██║  ██║╚════██╗
//  ██║   ██║██████╔╝█████╗  ██╔██╗ ██║███████║██████╔╝██║███████║ █████╔╝
//  ██║   ██║██╔═══╝ ██╔══╝  ██║╚██╗██║██╔══██║██╔═══╝ ██║╚════██║██╔═══╝ 
//  ╚██████╔╝██║     ███████╗██║ ╚████║██║  ██║██║     ██║     ██║███████╗
//   ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝     ╚═╝     ╚═╝╚══════╝
//                                                    -- www.OpenApi42.org
`.trim();

  const code = Code.fromNested(nestedCode);
  // const formattedCode = await prettier.format(code.toString(), {
  //   parser: "typescript",
  // });

  return `${banner}\n\n${code.toString()}`;
}
